targets:
  $default:
    builders:
      riverpod_generator:
        generate_for:
          - lib/**/*_provider.dart
      json_serializable:
        generate_for:
          - lib/transformers/**/*.dart
