name: release_builds

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  release_please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: dart
          package-name: vamonos-mgp
          release-search-depth: 5
          commit-search-depth: 5
    outputs:
      version: '${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}'

  # build_number:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     build_number: ${{ steps.buildnumber.outputs.build_number }}
  #   steps:
  #     - name: Generate build number
  #       id: buildnumber
  #       uses: onyxmueller/build-tag-number@v1
  #       with:
  #         token: ${{secrets.github_token}}

  # build_ios:
  #   needs:
  #     - build_number
  #     - release_please
  #   runs-on: macos-latest
  #   env:
  #     BUILD_NUMBER: '${{ needs.build_number.outputs.build_number }}'
  #     VERSION: '${{ needs.release_please.outputs.version }}'
  #     FLUTTER_VERSION: 3.7.12

  #   steps:
  #     - name: Print new build number
  #       run: echo "Build number is ${{ env.BUILD_NUMBER }}"

  #     - name: Checkout the code
  #       uses: actions/checkout@v2

  #     - name: Install and set Flutter version
  #       uses: subosito/flutter-action@v2.10.0
  #       with:
  #         flutter-version: '${{ env.FLUTTER_VERSION }}'
  #         cache: true

  #     - name: cache pub packages
  #       id: cache-pubdev
  #       uses: actions/cache@v3
  #       env:
  #         cache-name: cache-pubdev
  #       with:
  #         path: ~/.pub-cache
  #         key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('pubspec.lock') }}
  #         restore-keys: |
  #           ${{ runner.os }}-build-${{ env.cache-name }}

  #     - if: ${{ steps.cache-pubdev.outputs.cache-hit != 'true' }}
  #       name: pub cache miss/get deps
  #       continue-on-error: true
  #       run: |
  #         echo "Pub cache missed for ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('pubspec.lock') }}"
  #         flutter pub get

  #     - name: manually install cocoapods deps
  #       run: find . -name "Podfile" -execdir pod install \;

  #     - name: push to testflight beta
  #       env:
  #         APP_STORE_CONNECT_ISSUER_ID: '${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}'
  #         APP_STORE_CONNECT_KEY_IDENTIFIER: '${{ secrets.APP_STORE_CONNECT_KEY_IDENTIFIER }}'
  #         APP_STORE_CONNECT_PRIVATE_KEY_BASE64: '${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY_BASE64 }}'
  #       run: |
  #         export APP_STORE_CONNECT_PRIVATE_KEY_PATH=$RUNNER_TEMP/private_key.p8
  #         echo -n "$APP_STORE_CONNECT_PRIVATE_KEY_BASE64" | base64 --decode --output $APP_STORE_CONNECT_PRIVATE_KEY_PATH
  #         cd ios
  #         gem install bundler
  #         bundle install
  #         fastlane beta
